services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bacefook
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./modules/bacefook-api
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bacefook
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./modules/bacefook-api:/app
volumes:
  pgdata:
